### ISSUE TITLE
GripPointView hidden

### ISSUE THREAD

**Issue by Rufy86** [PKPK-Carnage/OTResizableView#1]
I would like show the view with the GripPointView showed. actually you can show them after the touch on the view. but to show them without the touch, at the start, How can I do it?

**Comment by Frog-Frog** [comment]
Thank you for using my library and sending issue.

If you want to display GripPointView, set "resizeEnabled" property of ResizableView to "true" when after addSubview.

Try this.
```swift
let resizableView = OTResizableView(contentView:yourView)
addSubview(resizableView)
resizableView.resizeEnabled = true
```

**Comment by Rufy86** [comment]
答えをありがとうございました。
Now It's working, because I set "resizeEnabled" property to "true" before  call "addSubview(resizableView) method. For this reason didn't work.
Thank you
