### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by fabiosoft** [PKPK-Carnage/OTResizableView#2]
I think the demo project is broken because no blue anchor points are visible and also If you don't enable the property, the view, doesn't move at all.

**Comment by Frog-Frog** [comment]
I could not find the broken part.
Can you attach an image(or gif animation) when it is broken, or tell me the situation in detail?

**Comment by fabiosoft** [comment]
Closing because now it's working. 
I could't find the property "resizeEnabled" in the example. I had to dig deeper into the class.
