### ISSUE TITLE
Cannot decrease the size less than 100x100 !

### ISSUE THREAD

**Issue by X901** [PKPK-Carnage/OTResizableView#3]
Hi , 
first of all thank you very much, the library working fine in Swift 4.2.1 
I think you need to mention this
because I was undecided to use the library 

anyway
I notice I cannot reduce the size less than 100 hight and 100 widget 
I try to modify the code 
but nothing working with me 
I don't know what it forced the view to not become less than 100 hight and 100 widget !

**Comment by Frog-Frog** [comment]
@X901 

Hi.
Sorry for the late reply.

Have you tried changing `minimumHeight` and `minimumWidth`?

It is possible to change the minimum size of ResizableView by changing it.

I hope this works well.

```swift

let resizableView = OTResizableView(contentView: yourView)
resizableView.delegate = self

// You  should change these values. 
resizableView.minimumWidth = 50
resizableView.minimumHeight = 50

view.addSubview(resizableView)

```

**Comment by X901** [comment]
When I Ask it wasn't work 
I did do clean and clean all
but also doesn't work 
after close Xcode and reopen it , it working fine 

Thank you
